# This workflow will build a Java project with Maven to ensure that no Unit-Test requires an infrastructure in some way
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven


name: Java 11 LTS (Unit-Tests only)

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against LTS Java version:
        java: [ '11' , '18' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}

    - name: Maven build
      run: mvn -DskipITs -B clean install

