# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      activemq:
        # Docker Hub image
        image: rmohr/activemq
        #
        ports:
          # Opens tcp port 6379 on the host and service container
          - 61616:61616
      postgres:
        # Docker Hub image
        image: postgres
        # setup default ports
        ports:
          # Opens tcp port 5432 on the host and service container
          - 5432:5432
        # setup default user for testing 
        env: 
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: admin

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
            
    - name: Maven build      
      env:
        GITHUB_USERNAME2: ${{ secrets.GITHUB_USERNAME2 }}  
        GITHUB_TOKEN2: ${{ secrets.GITHUB_TOKEN2 }}  
      run: mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml -B package --file pom.xml
    
    - name: Publish to GitHub Packages Apache Maven
      env:
        GITHUB_USERNAME2: ${{ secrets.GITHUB_USERNAME2 }}  
        GITHUB_TOKEN2: ${{ secrets.GITHUB_TOKEN2 }}  
        GITHUB_TOKEN: ${{ github.token }}
      run: mvn -s $GITHUB_WORKSPACE/.github/workflows/settings.xml deploy 
