# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven


name: Java Support CI

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # test against supported Java version:
        java: [ '11', '12', '13', '14', '15', '16', '17']

    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      activemq:
        # Docker Hub image
        image: rmohr/activemq
        #
        ports:
          # Opens tcp port 6379 on the host and service container
          - 61616:61616
      postgres:
        # Docker Hub image
        image: postgres
        # setup default ports
        ports:
          # Opens tcp port 5432 on the host and service container
          - 5432:5432
        # setup default user for testing
        env:
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: admin

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}

      - name: Maven build
        run: mvn '-Dmaven.compiler.release=${{ matrix.java }}' -B clean install

